### ISSUE TITLE
Posljednje stavke

### ISSUE THREAD

**Issue by danielvasic** [udruga-switch/fpmoz#1]
Tomo je li ovo zadnja verzija, kako ćemo povezati module. Treba li ista pomoći? Također pozovi i ostale da se pridruže ovdje da možemo se organizirati ako treba nešto.

**Comment by tkordic** [comment]
Moram stavit meteo jos, Hrvoje radi na modulima za nastavnike i nastavni
plan, a Brigita i Marija sadrzaj prenose.

Ako stignes posalji mi one slike za slider, na usb-u mi je samo ona s
bannerom, nemam onu sto je slikana iz zraka.

Dana 1. lis 2016. 08:18 osoba "Daniel Vasic" <notifications@github.com>
napisala je:

Tomo je li ovo zadnja verzija, kako ćemo povezati module. Treba li ista
pomoći? Također pozovi i ostale da se pridruže ovdje da možemo se
organizirati ako treba nešto.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/udruga-switch/fpmoz/issues/1>, or mute the thread

**Comment by danielvasic** [comment]
Podjeliti ću ti kad mi se učita na drive (velike su slike). @hrvamo kako stojimo sa modulima, meteo mogu i ja nije problem, trebalo bi na ove slike u footeru staviti linkove, a vidim da je slika u komadu, pa ako nije problem stavi likove da imamo manje problema, a ja ću meteo?

**Comment by tkordic** [comment]
Evo svejedno je skoro gotov meteo, sredit cu i te slike onda.

Dana 1. lis 2016. 08:50 osoba "Daniel Vasic" <notifications@github.com>
napisala je:

**Comment by danielvasic** [comment]
Super malo mi je spor internet pa kad se učita na drive cu ti share napraviti, računaj kroz nekih 20 min.

**Comment by danielvasic** [comment]
Za obavijesti zadnjih 10 vijesti kopirajte iz svake kategorije.
